import path from "path"
import { fileURLToPath } from "url"
import fs from "fs"
import Fastify from "fastify"
import fastifyStatic from "@fastify/static"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const PORT = process.env.PORT || 1331
const isProduction = process.env.NODE_ENV === "production"

// In production, serve from dist/client (static files generated by vite-plugin-ssr)
// In development, we'll rely on Vite dev server (run separately with npm run dev)
const publicDir = path.join(__dirname, isProduction ? "dist/client" : "public")

const fastify = Fastify({ logger: true })

// Serve static files
await fastify.register(fastifyStatic, {
    root: publicDir,
    prefix: "/",
    setHeaders: (res, filePath) => {
        const ext = path.extname(filePath).toLowerCase()
        if ([".html", ".css", ".js", ".png", ".jpg", ".jpeg", ".gif", ".svg"].includes(ext)) {
            res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
            res.setHeader("Pragma", "no-cache")
            res.setHeader("Expires", "0")
        } else if ([".woff", ".woff2", ".ttf", ".otf", ".eot"].includes(ext)) {
            res.setHeader("Cache-Control", "public, max-age=31536000, immutable")
        }
    }
})

// Inject font preload into HTML responses
fastify.addHook("onSend", async (request, reply, payload) => {
    try {
        const contentType = String(reply.getHeader("content-type") || reply.getHeader("Content-Type") || "")
        if (!/text\/html/i.test(contentType)) {
            return payload
        }

        const inject =
            '<link rel="preload" href="/NotoSans-VariableFont_wdth_wght.ttf" as="font" type="font/ttf" crossorigin>'

        if (Buffer.isBuffer(payload)) {
            let str = payload.toString("utf8")
            if (/<\/head>/i.test(str)) {
                str = str.replace(/<\/head>/i, `${inject}\n</head>`)
                return Buffer.from(str, "utf8")
            }
            return payload
        }

        if (typeof payload === "string") {
            if (/<\/head>/i.test(payload)) {
                return payload.replace(/<\/head>/i, `${inject}\n</head>`)
            }
            return payload
        }

        return payload
    } catch (err) {
        request.log.error({ msg: "onSend injection failed", error: err })
        return payload
    }
})

// Handle SPA routing - for any route that doesn't have a file, serve index.html
fastify.setNotFoundHandler(async (request, reply) => {
    const url = request.url
    // Skip API routes and file extensions (except .html)
    if (url.includes('.') && !url.endsWith('.html')) {
        // Likely a static file that doesn't exist
        reply.code(404).type("text/plain").send("404 Not Found")
        return
    }
    
    // For HTML routes, serve index.html (client-side routing will handle it)
    // In production with prerendering, this should only happen for non-prerendered dynamic routes
    const indexPath = path.join(publicDir, 'index.html')
    try {
        await fs.promises.access(indexPath, fs.constants.R_OK)
        const html = await fs.promises.readFile(indexPath, 'utf8')
        reply.type('text/html').send(html)
    } catch (err) {
        reply.code(404).type("text/plain").send("404 Not Found - index.html not found")
    }
})

// Start server
const start = async () => {
    try {
        await fastify.listen({ port: PORT, host: "::" })
        console.log(`Server running at http://localhost:${PORT}`)
        console.log(`Serving from: ${publicDir}`)
        console.log(`Mode: ${isProduction ? "production" : "development"}`)
        if (!isProduction) {
            console.log('Note: For development with hot reload, run "npm run dev" instead')
        }
    } catch (err) {
        console.error("Failed to start server:", err)
        process.exit(1)
    }
}

start()
